name: pdoc

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - develop

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - run: pip install -r requirements.txt
      - run: >
          pdoc --docformat google -o docs/
          db_object_config/db_object_config.py
          query_store/query_store.py
          query_store/synapse_query_store.py
          rdb_type/mysql.py
          rdb/rdb.py
          rdb_type/synapse.py
          rdb_queryer/rdb_queryer.py
          rdb_updater/rdb_updater.py
          schema/api_utils.py
          schema/schema.py
          synapse/synapse.py

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1